### ISSUE TITLE
actions布置完 aira2始终连接不上

### ISSUE THREAD

**Issue by jzysl423** [wy580477/Heroku-All-In-One-APP#10]
输了密码也连接不上
怎么查找问题所在

又被heroku封了吗

**Comment by wy580477** [comment]
1. ttyd输入sv status aria2，看aria2是不是正在运行。
2. 检查aria2 rpc路径，端口，协议是否正确。
3. shift＋f5强制刷新，再不行清除浏览器缓存和cookie。

**Comment by wy580477** [comment]
如果你以前部署过，现在更新到最新的main分支，有可能从rclone远端存储恢复了旧版的aria2.conf配置文件导致启动不了。
因为main分支换了yt-dlp，不需要提高aria2线程数来解决lux速度慢的问题，用回了官版aria2，如果恢复到旧版配置文件会因为线程数过高启动不了。
解决办法是把config目录下aria2.conf配置文件里面下载线程数从32改成16。

**Comment by jzysl423** [comment]
ttyd输入sv status aria2 显示run aria2 （pid 19）215s run log （pid18）215s
这代表什么意思

**Comment by jzysl423** [comment]
把协议改成https可以连上了
