### ISSUE TITLE
What Problem

### ISSUE THREAD

**Issue by kamileecher** [wy580477/Heroku-All-In-One-APP#11]
![Screenshot_2](https://user-images.githubusercontent.com/91373907/165404032-11b4e748-a4d2-4159-8aa3-377a5c65765f.png)

**Comment by wy580477** [comment]
Hit shift+F5 to force refresh. If it still doesn't work, clear cache and cookie of your heroku domain from browser.

**Comment by kamileecher** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/91373907/165567547-21781e66-fa11-4a4a-8e7f-17bbde4ce256.png)



bro how can i increase speed

**Comment by AmirulAndalib** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/91373907/165567547-21781e66-fa11-4a4a-8e7f-17bbde4ce256.png)
> 
> bro how can i increase speed

Torrent depends

**Comment by kamileecher** [comment]
In readme, it is written that torrent speed is limited in aria ng

**Comment by AmirulAndalib** [comment]
Yes you can increase with custom trackers for it you need some modification to code

**Comment by wy580477** [comment]
> bro how can i increase speed

There are three ways.

1. Edit /content/aria2/aria2_en.conf "max-overall-download-limit" option before deployment.
2. After deployment, edit aria2.conf "max-overall-download-limit" option through filebrowser under config folder. 
3. Click shoutcut button at the bottow of AriaNg page, then adjust global rate limit. This won't persist after dyno restarted.

High speed (>30MB/s) will result in high cpu/mem usage, your dyno could be forced to restart.

**Comment by AmirulAndalib** [comment]
> > bro how can i increase speed
> 
> There are three ways.
> 
> 1. Edit /content/aria2/aria2_en.conf "max-overall-download-limit" option before deployment.
> 2. After deployment, edit aria2.conf "max-overall-download-limit" option through filebrowser under config folder.
> 3. Click shoutcut button at the bottow of AriaNg page, then adjust global rate limit. This won't persist after dyno restarted.
> 
> High speed (>30MB/s) will result in high cpu/mem usage, your dyno could be forced to restart.

Heroku max speed is 70mbits now No crashes I used it myself +

You can save aria2config/ any other config that may get erased during Reboot you just need to modify some files and Docker stuff

**Comment by kamileecher** [comment]
yes i tested it too 70 mbps works great
