### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by gdhdhdh1441414** [wy580477/Heroku-All-In-One-APP#17]
1.你这个部署后，heroku无法登陆该app后台了 （heroku run bash -a APP_NAME）， 你可以测试

2.通过网页ttyd命令行下载的可执行文件，会提示找不到，但实际在，用ls和cat命令可以查看到，但执行文件时会提示文件不存在。可能ttyd无法实现，那请问该怎么修改源码，比如我想安装[BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go/releases) 在usr/bin

**Comment by wy580477** [comment]
> 1.你这个部署后，heroku无法登陆该app后台了 （heroku run bash -a APP_NAME）， 你可以测试

Dockerfile里面ENTRYPOINT项执行的命令占据了shell前台，正常现象。

> 2.通过网页ttyd命令行下载的可执行文件，会提示找不到，但实际在，用ls和cat命令可以查看到，但执行文件时会提示文件不存在。可能ttyd无法实现，那请问该怎么修改源码，比如我想安装[BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go/releases) 在usr/bin

试了一下确实有这个问题。但Heroku每24小时重置文件系统，需要增加执行文件本来就应该在部署前进行。

增加服务的话，在库内content/service目录下新建文件夹比如BaiduPCS，然后在此目录下新建run文件，按shell脚本语法写下载和执行程序的脚本。对外增加Web服务还需要在content目录下修改Caddyfile，增加反代设置。

Edit:
看了一下BaiduPCS-Go，这个不是以服务方式运行的，修改content目录下install_rclone.sh脚本，加上下载BaiduPCS-Go并解压到/usr/bin的命令就行了。

**Comment by gdhdhdh1441414** [comment]
我就是在install_rclone.sh加了这个，但还是一样提示文件不存在，查看/usr/bin目录有BaiduPCS-Go

**Comment by wy580477** [comment]
> 我就是在install_rclone.sh加了这个，但还是一样提示文件不存在，查看/usr/bin目录有BaiduPCS-Go

那就是缺库了，修改dockfile apk add那一行，增加gcompat试试，这是glibc兼容层。

![image](https://user-images.githubusercontent.com/98247050/168421571-fa7c3119-fa50-49f0-971a-2d37ba0a636a.png)

**Comment by gdhdhdh1441414** [comment]
是的  可以了

**Comment by gdhdhdh1441414** [comment]
Error relocating /usr/bin/zip: __wctomb_chk: symbol not found   这种呢？该怎么解决

**Comment by wy580477** [comment]
> Error relocating /usr/bin/zip: __wctomb_chk: symbol not found 这种呢？该怎么解决

有可能gcompat不够用。参考下面的dockerfile安装正经glibc试试

https://github.com/FuaerCN/Cloudreve-Heroku/blob/master/Dockerfile

**Comment by wy580477** [comment]
> Error relocating /usr/bin/zip: __wctomb_chk: symbol not found 这种呢？该怎么解决

建议以后提问先说操作步骤，不然我这里无法复现。

可以试试apk add zip看看。

**Comment by gdhdhdh1441414** [comment]
好！可以了，这个算是最完美的了。感谢！早几天heroku开始加强封号了，以前我搞的aria2c相关的基本被封完了，不知道这个能活多久，这种Template repository再fork的方法是不是能完全避免
