### ISSUE TITLE
不会配置rclone.conf

### ISSUE THREAD

**Issue by plok00286750** [wy580477/Heroku-All-In-One-APP#2]
挂载成功了但下载完没有上传

**Comment by wy580477** [comment]
如果Rclone Web UI能看到网盘里面的内容，打开heroku日志页面，下个文件看看什么情况。也可以看filebrowser里面log目录下aria2的日志。

注意 POST_MODE 变量默认move模式是不上传的，建议再阅读下变量说明。

**Comment by plok00286750** [comment]
成功上传了,可以改上传路径吗?或者可以上传到团队盘吗?

**Comment by wy580477** [comment]
> 成功上传了,可以改上传路径吗?或者可以上传到团队盘吗?

上传路径在部署前，仓库里面改/content/aria2/script.conf文件内容。

team盘看rclone官网配置指南：
https://rclone.org/drive/
