### ISSUE TITLE
Add Other

### ISSUE THREAD

**Issue by kamileecher** [wy580477/Heroku-All-In-One-APP#8]
https://github.com/ElonH/RcloneNg

https://github.com/developeranaz/Jdownloader-2-Rclone-Heroku

https://github.com/developeranaz/qbittorrent-to-rclone-heroku

**Comment by wy580477** [comment]
- I started this project with RcloneNg，then encountered slow dir refresh problem. So I switched to offical Rclone React WebUI.
  RcloneNg hasn't be updated for a while, so I won't consider add it unless it gets regular updates.
  If you want to use RcloneNg, you can connect to this app from RcloneNg running on other host 
  (https://elonh.github.io/RcloneNg for example)
- I'm looking into yt-dlp at the moment, thx for suggesting. 
- Consider heroku reboot & reset filesystem everyday, I don't see much advantage for specialized torrent downloader against aria2.

**Comment by kamileecher** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/91373907/164966629-14172715-96f3-4039-af0d-802e7a4819c3.png)
aria2c not work

**Comment by kamileecher** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/91373907/164966685-f29b2b24-763c-4c46-a66c-82b1ed5bb0e3.png)

**Comment by wy580477** [comment]
1. Click Aria2ng Setting
2. Fill Aria2 RPC key with ${PASSWORD} heroku env

**Comment by kamileecher** [comment]
is there a way how to get rpc key

**Comment by wy580477** [comment]
> is there a way how to get rpc key

It's the password which you fills when deploy to heroku.

**Comment by kamileecher** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/91373907/164967065-d7605a04-00b0-4d1f-8926-db0042a57e01.png)
I added rclone config, but how do I choose which cloud to upload to?

**Comment by wy580477** [comment]
>  I added rclone config, but how do I choose which cloud to upload to?

Depends on DRIVE_NAME env.

If it sets to "auto", then this app will use the first remote in config file.

Otherwise you can specify which remote by filling the remote name in DRIVE_NAME env.

**Comment by kamileecher** [comment]
It would be great if you add this kind of information to the readme. so that others don't ask again

**Comment by wy580477** [comment]
> It would be great if you add this kind of information to the readme. so that others don't ask again

It's in Readme. Perhaps something lost after machine tranlation.

I'll write an English version readme in the future.

**Comment by kamileecher** [comment]
bro what will you add other than ytdl?

**Comment by wy580477** [comment]
> bro what will you add other than ytdl?

Some ppl have been asking for telegram bot for controlling aria2/rclone/yt-dlp, I'm looking into after adding python telegram bot whether this project will get too big for heroku.

**Comment by kamileecher** [comment]
A project like this would be great. you can be inspired by mirror leech bots
